import { useEffect, useState } from 'react';
import { CheckCircle, XCircle, Clock, Calendar, Phone, Mail, MessageSquare, Loader2, Filter, Trash2, RefreshCw } from 'lucide-react';
import { api, type Booking, type Service } from '@/lib/api';
import { formatPrice, formatDate, formatTime, formatDateShort } from '@/lib/constants';

type BookingWithService = Booking & { services: Service | null };
type FilterStatus = 'all'|'pending'|'confirmed'|'completed'|'cancelled';
export default function AdminBookings(){
 const [bookings,setBookings]=useState<BookingWithService[]>([]),[loading,setLoading]=useState(true),[filter,setFilter]=useState<FilterStatus>('all'),[updating,setUpdating]=useState<string|null>(null),[selectedBooking,setSelectedBooking]=useState<BookingWithService|null>(null),[error,setError]=useState<string|null>(null);
 const fetchBookings=async()=>{setLoading(true);setError(null);try{setBookings(await api.bookings.getAll())}catch(e){setError(e instanceof Error?e.message:'Unable to load bookings.')}finally{setLoading(false)}};
 useEffect(()=>{fetchBookings()},[]);
 const updateStatus=async(id:string,status:Booking['status'])=>{setUpdating(id);setError(null);try{const updated=await api.bookings.updateStatus(id,status);setBookings(p=>p.map(b=>b.id===id?{...b,...updated,status}:b));setSelectedBooking(p=>p?.id===id?{...p,...updated,status}:p)}catch(e){setError(e instanceof Error?e.message:'Failed to update booking.')}finally{setUpdating(null)}};
 const deleteBooking=async(id:string)=>{if(!confirm('Delete this booking permanently? This cannot be undone.'))return;setUpdating(id);setError(null);try{await api.bookings.delete(id);setBookings(p=>p.filter(b=>b.id!==id));if(selectedBooking?.id===id)setSelectedBooking(null)}catch(e){setError(e instanceof Error?e.message:'Failed to delete booking.')}finally{setUpdating(null)}};
 const filtered=filter==='all'?bookings:bookings.filter(b=>b.status===filter);
 const tabs:[string,FilterStatus][]=[['All','all'],['Pending','pending'],['Confirmed','confirmed'],['Completed','completed'],['Cancelled','cancelled']];
 return <div className="space-y-6"><div className="flex items-end justify-between gap-4"><div><h2 className="font-display text-3xl text-ink-50">Bookings</h2><p className="mt-1 text-ink-400">Manage all customer appointments</p></div><button onClick={fetchBookings} className="btn-outline !py-2.5"><RefreshCw className="h-4 w-4"/>Refresh</button></div>{error&&<div className="flex items-center gap-2 rounded-xl border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-400">{error}</div>}
 <div className="flex flex-wrap gap-2">{tabs.map(([label,value])=>{const count=value==='all'?bookings.length:bookings.filter(b=>b.status===value).length;return <button key={value} onClick={()=>setFilter(value)} className={`flex items-center gap-2 rounded-full px-4 py-2 text-sm font-medium ${filter===value?'bg-gold-500 text-ink-950':'border border-ink-600 text-ink-300 hover:border-gold-500/40'}`}>{label}<span className="rounded-full bg-ink-800/50 px-2 py-0.5 text-xs">{count}</span></button>})}</div>
 {loading?<div className="flex items-center justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-gold-500"/></div>:!filtered.length?<div className="rounded-2xl border border-ink-700 bg-ink-900 py-16 text-center"><Filter className="mx-auto mb-3 h-8 w-8 text-ink-600"/><p className="text-ink-400">No {filter!=='all'?filter+' ':''}bookings found.</p></div>:<div className="space-y-3">{filtered.map(b=><div key={b.id} className="rounded-2xl border border-ink-700 bg-ink-900 p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-gold-500/10"><Calendar className="h-5 w-5 text-gold-500"/></div><div><div className="flex items-center gap-2"><h3 className="font-semibold text-ink-50">{b.customer_name}</h3><span className="rounded-full bg-ink-800 px-3 py-1 text-xs text-ink-300">{b.status}</span></div><p className="mt-0.5 text-sm text-ink-400">{b.services?.name||'Service'} · {formatPrice(Number(b.services?.price||0))}</p><p className="mt-0.5 text-xs text-ink-500">{formatDateShort(b.booking_date)} at {formatTime(b.booking_time)}</p></div></div><div className="flex flex-wrap gap-2">{b.status==='pending'&&<button onClick={()=>updateStatus(b.id,'confirmed')} disabled={updating===b.id} className="rounded-full bg-green-500/10 px-4 py-2 text-xs font-semibold text-green-400 disabled:opacity-50"><CheckCircle className="mr-1 inline h-3.5 w-3.5"/>Accept</button>}{b.status==='confirmed'&&<button onClick={()=>updateStatus(b.id,'completed')} disabled={updating===b.id} className="rounded-full bg-blue-500/10 px-4 py-2 text-xs font-semibold text-blue-400 disabled:opacity-50"><CheckCircle className="mr-1 inline h-3.5 w-3.5"/>Complete</button>}{(b.status==='pending'||b.status==='confirmed')&&<button onClick={()=>updateStatus(b.id,'cancelled')} disabled={updating===b.id} className="rounded-full bg-red-500/10 px-4 py-2 text-xs font-semibold text-red-400 disabled:opacity-50"><XCircle className="mr-1 inline h-3.5 w-3.5"/>Cancel</button>}{b.status==='cancelled'&&<button onClick={()=>updateStatus(b.id,'pending')} disabled={updating===b.id} className="rounded-full bg-accent-500/10 px-4 py-2 text-xs font-semibold text-accent-400 disabled:opacity-50"><Clock className="mr-1 inline h-3.5 w-3.5"/>Reactivate</button>}<button onClick={()=>setSelectedBooking(b)} className="rounded-full border border-ink-600 px-4 py-2 text-xs font-semibold text-ink-200 hover:border-gold-500">Details</button><button onClick={()=>deleteBooking(b.id)} disabled={updating===b.id} className="rounded-full border border-ink-600 px-3 py-2 text-xs text-ink-400 hover:border-red-500 hover:text-red-400"><Trash2 className="h-3.5 w-3.5"/></button></div></div></div>)}</div>}
 {selectedBooking&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-ink-950/80 px-5 py-8" onClick={()=>setSelectedBooking(null)}><div className="w-full max-w-lg rounded-2xl border border-ink-700 bg-ink-900 p-6" onClick={e=>e.stopPropagation()}><div className="mb-6 flex items-center justify-between"><h3 className="font-display text-2xl text-ink-50">Booking Details</h3><button onClick={()=>setSelectedBooking(null)} className="text-ink-400"><XCircle className="h-5 w-5"/></button></div><div className="space-y-4"><Row icon={Calendar} label="Service" value={selectedBooking.services?.name||'—'}/><Row icon={Calendar} label="Date" value={formatDate(selectedBooking.booking_date)}/><Row icon={Clock} label="Time" value={formatTime(selectedBooking.booking_time)}/><Row icon={Clock} label="Price" value={formatPrice(Number(selectedBooking.services?.price||0))}/><Row icon={Phone} label="Phone" value={selectedBooking.customer_phone}/>{selectedBooking.customer_email&&<Row icon={Mail} label="Email" value={selectedBooking.customer_email}/>}<Row icon={Clock} label="Booked on" value={formatDateShort(selectedBooking.created_at)}/>{selectedBooking.notes&&<div className="border-t border-ink-700 pt-4"><div className="mb-1 flex items-center gap-2 text-sm text-ink-400"><MessageSquare className="h-4 w-4 text-gold-500"/>Notes</div><p className="rounded-xl bg-ink-950 p-3 text-sm text-ink-200">{selectedBooking.notes}</p></div>}<div className="border-t border-ink-700 pt-4"><div className="mb-1 text-sm text-ink-400">Status</div><span className="rounded-full bg-ink-800 px-3 py-1 text-xs text-ink-300">{selectedBooking.status}</span></div></div><div className="mt-6"><a href={`tel:${selectedBooking.customer_phone}`} className="btn-outline w-full"><Phone className="h-4 w-4"/>Call Customer</a></div></div></div>}
 </div>;
}
function Row({icon:Icon,label,value}:{icon:React.ComponentType<{className?:string}>;label:string;value:string}){return <div className="flex items-center justify-between gap-4"><span className="flex items-center gap-2 text-sm text-ink-400"><Icon className="h-4 w-4 text-gold-500"/>{label}</span><span className="text-right text-sm font-medium text-ink-100">{value}</span></div>}
