import { useEffect, useState } from 'react';
import { Calendar, Clock, CheckCircle, Users, DollarSign, Scissors, Loader2, RefreshCw } from 'lucide-react';
import { api, type BookingWithService } from '@/lib/api';
import { formatPrice, formatDateShort, formatTime } from '@/lib/constants';

type Overview = { pending_count: string|number; confirmed_count: string|number; completed_count: string|number; cancelled_count: string|number; today_count: string|number; total_services: string|number; total_revenue: string|number; recent_bookings: BookingWithService[] };
export default function AdminOverview() {
  const [data,setData]=useState<Overview|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  const load=async()=>{setLoading(true);setError(null);try{setData(await api.overview.get() as Overview)}catch(e){setError(e instanceof Error?e.message:'Unable to load dashboard.')}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  if(loading)return <div className="flex items-center justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-gold-500"/></div>;
  if(error)return <div className="mx-auto mt-10 max-w-lg rounded-2xl border border-ink-700 bg-ink-900 p-8 text-center"><p className="text-ink-300">{error}</p><button onClick={load} className="btn-outline mt-5"><RefreshCw className="h-4 w-4"/>Retry</button></div>;
  if(!data)return null;
  const stats=[['Today',data.today_count,Calendar,'text-gold-500'],['Pending',data.pending_count,Clock,'text-accent-500'],['Confirmed',data.confirmed_count,CheckCircle,'text-green-500'],['Completed',data.completed_count,Users,'text-blue-500']];
  return <div className="space-y-6"><div className="flex items-end justify-between gap-4"><div><h2 className="font-display text-3xl text-ink-50">Dashboard</h2><p className="mt-1 text-ink-400">Overview of your barbershop activity</p></div><button onClick={load} className="btn-outline !py-2.5">Refresh</button></div>
    <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{stats.map(([label,value,Icon,color])=>{const I=Icon as typeof Calendar;return <div key={String(label)} className="rounded-2xl border border-ink-700 bg-ink-900 p-5"><div className="flex items-center justify-between"><I className={`h-6 w-6 ${color}`}/><span className="font-display text-3xl font-bold text-ink-50">{value}</span></div><p className="mt-2 text-sm text-ink-400">{label}</p></div>})}</div>
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-green-500/20 bg-green-500/5 p-5"><div className="flex items-center gap-3"><DollarSign className="h-6 w-6 text-green-500"/><div><p className="text-sm text-ink-400">Completed Revenue</p><p className="font-display text-2xl font-bold text-ink-50">{formatPrice(Number(data.total_revenue))}</p></div></div></div><div className="rounded-2xl border border-gold-500/20 bg-gold-500/5 p-5"><div className="flex items-center gap-3"><Scissors className="h-6 w-6 text-gold-500"/><div><p className="text-sm text-ink-400">Active Services</p><p className="font-display text-2xl font-bold text-ink-50">{data.total_services}</p></div></div></div></div>
    <div className="rounded-2xl border border-ink-700 bg-ink-900 p-6"><h3 className="mb-4 flex items-center gap-2 font-display text-xl text-ink-50"><Calendar className="h-5 w-5 text-gold-500"/>Recent Bookings</h3>{data.recent_bookings?.length? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-ink-700 text-ink-400"><th className="pb-3 pr-4 font-medium">Customer</th><th className="pb-3 pr-4 font-medium">Service</th><th className="pb-3 pr-4 font-medium">Date</th><th className="pb-3 pr-4 font-medium">Time</th><th className="pb-3 font-medium">Status</th></tr></thead><tbody>{data.recent_bookings.map(b=><tr key={b.id} className="border-b border-ink-700/50"><td className="py-3 pr-4 text-ink-100">{b.customer_name}</td><td className="py-3 pr-4 text-ink-300">{b.services?.name||'—'}</td><td className="py-3 pr-4 text-ink-300">{formatDateShort(b.booking_date)}</td><td className="py-3 pr-4 text-ink-300">{formatTime(b.booking_time)}</td><td className="py-3"><span className="rounded-full bg-ink-800 px-3 py-1 text-xs text-ink-300">{b.status}</span></td></tr>)}</tbody></table></div>:<p className="py-8 text-center text-sm text-ink-500">No bookings yet.</p>}</div>
  </div>;
}
