import { useState } from 'react';
import { Lock, Loader2, Check, AlertCircle, Eye, EyeOff } from 'lucide-react';
import { api } from '@/lib/api';

export default function AdminPassword() {
  const [currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null),[success,setSuccess]=useState(false),[show,setShow]=useState(false);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError(null);setSuccess(false);if(!currentPassword||!newPassword||!confirmPassword)return setError('Please fill in all fields.');if(newPassword.length<8)return setError('New password must be at least 8 characters.');if(newPassword!==confirmPassword)return setError('New passwords do not match.');if(newPassword===currentPassword)return setError('New password must be different from current password.');setLoading(true);try{const result=await api.auth.changePassword(currentPassword,newPassword) as {hash?:string};setSuccess(true);setCurrentPassword('');setNewPassword('');setConfirmPassword('');if(result.hash)setError(`New hash generated. Replace ADMIN_PASSWORD_HASH in the server environment with the returned hash.`)}catch(err){setError(err instanceof Error?err.message:'Failed to update password.')}finally{setLoading(false)}};
  return <div className="space-y-6"><div><h2 className="font-display text-3xl text-ink-50">Change Password</h2><p className="mt-1 text-ink-400">Update your admin login password</p></div><div className="max-w-md rounded-2xl border border-ink-700 bg-ink-900 p-6 sm:p-8"><form onSubmit={submit} className="space-y-4">{[['Current Password',currentPassword,setCurrentPassword],['New Password',newPassword,setNewPassword],['Confirm New Password',confirmPassword,setConfirmPassword]].map(([label,value,setValue],i)=><label key={String(label)} className="block text-sm text-ink-300">{label}<div className="relative"><input type={show?'text':'password'} value={value as string} onChange={e=>(setValue as (v:string)=>void)(e.target.value)} className="mt-1 w-full rounded-xl border border-ink-600 bg-ink-950 px-4 py-3 pr-10 text-ink-100"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-1/2 mt-0.5 -translate-y-1/2 text-ink-500">{show?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></div></label>)}{error&&<div className="flex items-start gap-2 rounded-lg border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-400"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0"/>{error}</div>}{success&&<div className="flex items-center gap-2 rounded-lg border border-green-500/30 bg-green-500/10 px-4 py-3 text-sm text-green-400"><Check className="h-4 w-4"/>Password update request processed.</div>}<button type="submit" disabled={loading} className="btn-gold w-full">{loading?<><Loader2 className="h-4 w-4 animate-spin"/>Updating...</>:<><Lock className="h-4 w-4"/>Update Password</>}</button></form></div></div>;
}
