import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import { neon } from '@neondatabase/serverless';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import { createServer } from 'http';

const app = express();
const httpServer = createServer(app);
const DB_URL = process.env.DATABASE_URL;
const JWT_SECRET = process.env.JWT_SECRET || 'lena-cutz-dev-secret';
const ADMIN_EMAIL = process.env.ADMIN_EMAIL || 'juditheberechi274@gmail.com';
const ADMIN_PASSWORD_HASH = process.env.ADMIN_PASSWORD_HASH || '';
const ADMIN_PASSWORD_PLAIN = process.env.ADMIN_PASSWORD_PLAIN || '';
const PORT = Number(process.env.PORT) || 3001;
if (!DB_URL) { console.error('ERROR: DATABASE_URL is not set.'); process.exit(1); }
const sql = neon(DB_URL);
const allowedOrigins = (process.env.CORS_ORIGIN || '').split(',').map((v) => v.trim()).filter(Boolean);
app.use(cors({ origin: allowedOrigins.length ? allowedOrigins : true, credentials: true }));
app.use(express.json({ limit: '1mb' }));

function requireAuth(req,res,next){const auth=req.headers.authorization;if(!auth?.startsWith('Bearer '))return res.status(401).json({error:'Unauthorized'});try{req.admin=jwt.verify(auth.slice(7),JWT_SECRET);next()}catch{return res.status(401).json({error:'Invalid or expired token'})}}
async function getAdminCredentials(){const rows=await sql`SELECT email,password_hash FROM admin_credentials WHERE id=1 LIMIT 1`;if(rows.length)return rows[0];if(ADMIN_PASSWORD_HASH||ADMIN_PASSWORD_PLAIN)return{email:ADMIN_EMAIL,password_hash:ADMIN_PASSWORD_HASH||await bcrypt.hash(ADMIN_PASSWORD_PLAIN,10)};return null}
function cleanImageUrl(value){const image=value==null?'':String(value).trim();if(!image)return null;if(image.startsWith('data:image/')){if(image.length>900000)throw new Error('Image is too large. Please choose an image under 650 KB.');return image;}if(!/^https?:\/\//i.test(image))throw new Error('Image must be an uploaded image or a valid image URL.');return image;}

app.get('/api/health',async(_req,res)=>{try{await sql`SELECT 1`;res.json({status:'ok',db:'connected',provider:'neon'})}catch(err){console.error('Health check failed:',err);res.status(500).json({status:'error',db:'disconnected',error:'Database unavailable'})}});

app.post('/api/auth/login',async(req,res)=>{const email=String(req.body?.email||'').trim(),password=String(req.body?.password||'');if(!email||!password)return res.status(400).json({error:'Email and password required.'});try{const admin=await getAdminCredentials();if(!admin||email.toLowerCase()!==admin.email.toLowerCase())return res.status(401).json({error:'Wrong email or password. Please try again.'});if(!(await bcrypt.compare(password,admin.password_hash)))return res.status(401).json({error:'Wrong email or password. Please try again.'});const token=jwt.sign({email:admin.email},JWT_SECRET,{expiresIn:'12h'});res.json({token,email:admin.email})}catch(err){console.error('Login failed:',err);res.status(500).json({error:'Unable to sign in right now.'})}});

app.post('/api/auth/change-password',requireAuth,async(req,res)=>{const currentPassword=String(req.body?.currentPassword||''),newPassword=String(req.body?.newPassword||'');if(!currentPassword||!newPassword)return res.status(400).json({error:'Both passwords required.'});if(newPassword.length<8)return res.status(400).json({error:'New password must be at least 8 characters.'});try{const admin=await getAdminCredentials();if(!admin||!(await bcrypt.compare(currentPassword,admin.password_hash)))return res.status(401).json({error:'Current password is incorrect.'});const hash=await bcrypt.hash(newPassword,10);await sql`INSERT INTO admin_credentials (id,email,password_hash,updated_at) VALUES (1,${admin.email},${hash},NOW()) ON CONFLICT (id) DO UPDATE SET password_hash=EXCLUDED.password_hash,email=EXCLUDED.email,updated_at=NOW()`;res.json({message:'Password changed successfully.'})}catch(err){console.error('Change password failed:',err);res.status(500).json({error:'Failed to change password.'})}});

app.get('/api/categories',async(_req,res)=>{try{res.json(await sql`SELECT id,name,created_at FROM categories ORDER BY name ASC`)}catch(err){console.error('Public categories failed:',err);res.status(500).json({error:'Failed to fetch categories.'})}});
app.get('/api/admin/categories',requireAuth,async(_req,res)=>{try{res.json(await sql`SELECT c.id,c.name,c.created_at,COUNT(s.id)::int AS service_count FROM categories c LEFT JOIN services s ON s.category_id=c.id GROUP BY c.id ORDER BY c.name ASC`)}catch(err){console.error('Admin categories failed:',err);res.status(500).json({error:'Failed to fetch categories.'})}});
app.post('/api/admin/categories',requireAuth,async(req,res)=>{const name=String(req.body?.name||'').trim();if(!name)return res.status(400).json({error:'Category name is required.'});if(name.length>60)return res.status(400).json({error:'Category name is too long.'});try{const rows=await sql`INSERT INTO categories (name) VALUES (${name}) RETURNING id,name,created_at`;res.status(201).json(rows[0])}catch(err){if(err?.code==='23505')return res.status(409).json({error:'That category already exists.'});console.error('Create category failed:',err);res.status(500).json({error:'Failed to create category.'})}});
app.patch('/api/admin/categories/:id',requireAuth,async(req,res)=>{const name=String(req.body?.name||'').trim();if(!name)return res.status(400).json({error:'Category name is required.'});try{const rows=await sql`UPDATE categories SET name=${name} WHERE id=${req.params.id} RETURNING id,name,created_at`;if(!rows.length)return res.status(404).json({error:'Category not found.'});res.json(rows[0])}catch(err){if(err?.code==='23505')return res.status(409).json({error:'That category already exists.'});console.error('Update category failed:',err);res.status(500).json({error:'Failed to update category.'})}});
app.delete('/api/admin/categories/:id',requireAuth,async(req,res)=>{try{const rows=await sql`DELETE FROM categories WHERE id=${req.params.id} RETURNING id`;if(!rows.length)return res.status(404).json({error:'Category not found.'});res.json({success:true})}catch(err){console.error('Delete category failed:',err);res.status(500).json({error:'Failed to delete category.'})}});

const serviceSelect=sql`SELECT s.*,c.name AS category_name FROM services s LEFT JOIN categories c ON c.id=s.category_id`;
app.get('/api/services',async(_req,res)=>{try{res.json(await sql`SELECT s.*,c.name AS category_name FROM services s LEFT JOIN categories c ON c.id=s.category_id WHERE s.is_active=true ORDER BY s.sort_order ASC,s.created_at ASC`)}catch(err){console.error('Public services failed:',err);res.status(500).json({error:'Failed to fetch services.'})}});
app.get('/api/admin/services',requireAuth,async(_req,res)=>{try{res.json(await sql`SELECT s.*,c.name AS category_name FROM services s LEFT JOIN categories c ON c.id=s.category_id ORDER BY s.sort_order ASC,s.created_at ASC`)}catch(err){console.error('Admin services failed:',err);res.status(500).json({error:'Failed to fetch services.'})}});
app.post('/api/admin/services',requireAuth,async(req,res)=>{const{ name,description,duration_minutes,price,image_url,sort_order,is_active,category_id}=req.body||{};const duration=Number(duration_minutes),amount=Number(price);if(!String(name||'').trim()||!Number.isFinite(duration)||duration<=0||!Number.isFinite(amount)||amount<0)return res.status(400).json({error:'name, duration_minutes and a valid price are required.'});try{const image=cleanImageUrl(image_url);const rows=await sql`INSERT INTO services (name,description,duration_minutes,price,image_url,sort_order,is_active,category_id) VALUES (${String(name).trim()},${description?String(description).trim():null},${duration},${amount},${image},${Number(sort_order)||0},${is_active!==false},${category_id||null}) RETURNING *`;res.status(201).json(rows[0])}catch(err){console.error('Create service failed:',err);res.status(500).json({error:err?.message?.includes('Image')?err.message:'Failed to create service.'})}});
app.patch('/api/admin/services/:id',requireAuth,async(req,res)=>{const body=req.body||{},id=req.params.id;try{const name=body.name===undefined?null:String(body.name).trim(),description=body.description===undefined?null:(body.description===''?null:String(body.description).trim()),duration=body.duration_minutes===undefined?null:Number(body.duration_minutes),price=body.price===undefined?null:Number(body.price),sortOrder=body.sort_order===undefined?null:Number(body.sort_order),active=body.is_active===undefined?null:Boolean(body.is_active),categoryId=body.category_id===undefined?null:(body.category_id||null),image=body.image_url===undefined?null:cleanImageUrl(body.image_url);if(duration!==null&&(!Number.isFinite(duration)||duration<=0))return res.status(400).json({error:'Duration must be a positive number.'});if(price!==null&&(!Number.isFinite(price)||price<0))return res.status(400).json({error:'Price must be a valid non-negative number.'});const rows=await sql`UPDATE services SET name=COALESCE(${name},name),description=CASE WHEN ${body.description!==undefined} THEN ${description} ELSE description END,duration_minutes=COALESCE(${duration},duration_minutes),price=COALESCE(${price},price),image_url=CASE WHEN ${body.image_url!==undefined} THEN ${image} ELSE image_url END,sort_order=COALESCE(${sortOrder},sort_order),is_active=COALESCE(${active},is_active),category_id=CASE WHEN ${body.category_id!==undefined} THEN ${categoryId} ELSE category_id END WHERE id=${id} RETURNING *`;if(!rows.length)return res.status(404).json({error:'Service not found.'});res.json(rows[0])}catch(err){console.error('Update service failed:',err);res.status(500).json({error:err?.message?.includes('Image')?err.message:'Failed to update service.'})}});
app.delete('/api/admin/services/:id',requireAuth,async(req,res)=>{try{const rows=await sql`DELETE FROM services WHERE id=${req.params.id} RETURNING id`;if(!rows.length)return res.status(404).json({error:'Service not found.'});res.json({success:true})}catch(err){console.error('Delete service failed:',err);res.status(500).json({error:'Failed to delete service.'})}});

app.get('/api/availability',async(req,res)=>{const date=String(req.query?.date||'').trim(),serviceId=String(req.query?.service_id||'').trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return res.status(400).json({error:'A valid date (YYYY-MM-DD) is required.'});try{const rows=await sql`SELECT to_char(booking_time,'HH24:MI') AS booking_time FROM bookings WHERE booking_date=${date} AND status IN ('pending','confirmed') ${serviceId?sql`AND service_id=${serviceId}`:sql``}`;res.json({date,booked_slots:rows.map(r=>r.booking_time)})}catch(err){console.error('Availability failed:',err);res.status(500).json({error:'Failed to fetch availability.'})}});

app.post('/api/bookings',async(req,res)=>{const{service_id,customer_name,customer_phone,customer_email,booking_date,booking_time,notes}=req.body||{};if(!service_id||!customer_name||!customer_phone||!booking_date||!booking_time)return res.status(400).json({error:'Missing required booking fields.'});try{const service=await sql`SELECT id FROM services WHERE id=${service_id} AND is_active=true LIMIT 1`;if(!service.length)return res.status(400).json({error:'Selected service is no longer available.'});const conflict=await sql`SELECT id FROM bookings WHERE booking_date=${booking_date} AND booking_time=${booking_time} AND status IN ('pending','confirmed') LIMIT 1`;if(conflict.length)return res.status(409).json({error:'That time has already been booked. Please choose another time.'});const rows=await sql`INSERT INTO bookings (service_id,customer_name,customer_phone,customer_email,booking_date,booking_time,notes,status) VALUES (${service_id},${String(customer_name).trim()},${String(customer_phone).trim()},${customer_email?String(customer_email).trim():null},${booking_date},${booking_time},${notes?String(notes).trim():null},'pending') RETURNING *`;res.status(201).json(rows[0])}catch(err){console.error('Create booking failed:',err);if(err?.code==='23505')return res.status(409).json({error:'That time has already been booked. Please choose another time.'});res.status(500).json({error:'Failed to create booking.'})}});
app.get('/api/admin/bookings',requireAuth,async(_req,res)=>{try{const rows=await sql`SELECT b.*,CASE WHEN s.id IS NULL THEN NULL ELSE json_build_object('id',s.id,'name',s.name,'price',s.price,'duration_minutes',s.duration_minutes,'description',s.description,'image_url',s.image_url,'sort_order',s.sort_order,'is_active',s.is_active,'created_at',s.created_at,'category_id',s.category_id,'category_name',c.name) END AS services FROM bookings b LEFT JOIN services s ON b.service_id=s.id LEFT JOIN categories c ON c.id=s.category_id ORDER BY b.booking_date DESC,b.booking_time ASC,b.created_at DESC`;res.json(rows)}catch(err){console.error('Admin bookings failed:',err);res.status(500).json({error:'Failed to fetch bookings.'})}});
app.patch('/api/admin/bookings/:id/status',requireAuth,async(req,res)=>{const status=req.body?.status;if(!['pending','confirmed','cancelled','completed'].includes(status))return res.status(400).json({error:'Invalid status.'});try{const rows=await sql`UPDATE bookings SET status=${status} WHERE id=${req.params.id} RETURNING *`;if(!rows.length)return res.status(404).json({error:'Booking not found.'});res.json(rows[0])}catch(err){console.error('Update booking failed:',err);res.status(500).json({error:'Failed to update booking status.'})}});
app.delete('/api/admin/bookings/:id',requireAuth,async(req,res)=>{try{const rows=await sql`DELETE FROM bookings WHERE id=${req.params.id} RETURNING id`;if(!rows.length)return res.status(404).json({error:'Booking not found.'});res.json({success:true})}catch(err){console.error('Delete booking failed:',err);res.status(500).json({error:'Failed to delete booking.'})}});

app.get('/api/settings',async(_req,res)=>{try{const rows=await sql`SELECT * FROM salon_settings ORDER BY id ASC LIMIT 1`;res.json(rows[0]||null)}catch(err){console.error('Get settings failed:',err);res.status(500).json({error:'Failed to fetch settings.'})}});
app.patch('/api/admin/settings',requireAuth,async(req,res)=>{const fields=req.body||{},allowed=['salon_name','phone','email','location','instagram','whatsapp','bank_name','account_name','account_number','mon_fri_hours','sat_hours','sun_hours'],clean=Object.fromEntries(Object.entries(fields).filter(([k])=>allowed.includes(k)));if(!Object.keys(clean).length)return res.status(400).json({error:'No valid fields provided.'});try{const existing=await sql`SELECT id FROM salon_settings ORDER BY id ASC LIMIT 1`;let rows;if(!existing.length)rows=await sql`INSERT INTO salon_settings (salon_name,phone,email,location,instagram,whatsapp,bank_name,account_name,account_number,mon_fri_hours,sat_hours,sun_hours) VALUES (${clean.salon_name||'Lena Cutz'},${clean.phone||''},${clean.email||''},${clean.location||''},${clean.instagram||''},${clean.whatsapp||''},${clean.bank_name||null},${clean.account_name||null},${clean.account_number||null},${clean.mon_fri_hours||'8:00 AM – 8:00 PM'},${clean.sat_hours||'8:00 AM – 9:00 PM'},${clean.sun_hours||'12:00 PM – 6:00 PM'}) RETURNING *`;else rows=await sql`UPDATE salon_settings SET salon_name=COALESCE(${clean.salon_name??null},salon_name),phone=COALESCE(${clean.phone??null},phone),email=COALESCE(${clean.email??null},email),location=COALESCE(${clean.location??null},location),instagram=COALESCE(${clean.instagram??null},instagram),whatsapp=COALESCE(${clean.whatsapp??null},whatsapp),bank_name=CASE WHEN ${Object.prototype.hasOwnProperty.call(clean,'bank_name')} THEN ${clean.bank_name||null} ELSE bank_name END,account_name=CASE WHEN ${Object.prototype.hasOwnProperty.call(clean,'account_name')} THEN ${clean.account_name||null} ELSE account_name END,account_number=CASE WHEN ${Object.prototype.hasOwnProperty.call(clean,'account_number')} THEN ${clean.account_number||null} ELSE account_number END,mon_fri_hours=COALESCE(${clean.mon_fri_hours??null},mon_fri_hours),sat_hours=COALESCE(${clean.sat_hours??null},sat_hours),sun_hours=COALESCE(${clean.sun_hours??null},sun_hours),updated_at=NOW() WHERE id=${existing[0].id} RETURNING *`;res.json(rows[0])}catch(err){console.error('Update settings failed:',err);res.status(500).json({error:'Failed to update settings.'})}});

app.get('/api/admin/overview',requireAuth,async(_req,res)=>{try{const[stats]=await sql`SELECT COUNT(*) FILTER (WHERE status='pending') AS pending_count,COUNT(*) FILTER (WHERE status='confirmed') AS confirmed_count,COUNT(*) FILTER (WHERE status='completed') AS completed_count,COUNT(*) FILTER (WHERE status='cancelled') AS cancelled_count,COUNT(*) FILTER (WHERE booking_date=CURRENT_DATE) AS today_count,COALESCE(SUM(s.price) FILTER (WHERE b.status='completed'),0) AS total_revenue FROM bookings b LEFT JOIN services s ON b.service_id=s.id`;const[serviceStats]=await sql`SELECT COUNT(*) FILTER (WHERE is_active=true) AS total FROM services`;const recent=await sql`SELECT b.*,CASE WHEN s.id IS NULL THEN NULL ELSE json_build_object('id',s.id,'name',s.name,'price',s.price,'duration_minutes',s.duration_minutes) END AS services FROM bookings b LEFT JOIN services s ON b.service_id=s.id ORDER BY b.created_at DESC LIMIT 8`;res.json({...stats,total_services:serviceStats.total,recent_bookings:recent})}catch(err){console.error('Overview failed:',err);res.status(500).json({error:'Failed to fetch overview.'})}});

httpServer.listen(PORT,()=>console.log(`✅ Lena Cutz API listening on port ${PORT}`));
